create table Family (
    primary key id,
    FamilyFirstName varchar (50) not null,
    FamilyLastName varchar (50) not null,
    FamilyBirthday varchar (50) not null,
    FamilyWebsite varchar (100) not null,
    FamilyEmail varchar (100) not null,
    FamilyPhoneNumber int not null,
    FamilyAddress varchar (150) not null,
    FamilyCity varchar (50) not null,
    FamilyState varchar (100) not null,
    FamilyCountry varchar (50) not null,
    FamilyContinent varchar (100) not null,
    FamilyPlanet varchar (200) not null,
    FamilyFavoriteColor varchar (50) not null,
    FamilyFavoriteFood varchar (100) not null,
    FamilyFavoriteDrink varchar (150) not null,
    FamilyHobby varchar (100) not null,
    FamilyTalent varchar (100) not null,
    FamilyZodiacSign varchar (100) not null,
    FamilyChineseZodiac varchar (100) not null,
    FamilyDISC varchar (50) not null,
    FamilyBusinessPersonalityType varchar (50) not null,
    FamilyLearningType varchar (50) not null,
    FamilyLoveLanguage varchar (50) not null,
    FamilySpiritAnimal varchar (100) not null,
    FamilyLifeDreamGoal varchar (100) not null,
    FamilyFavoriteSport varchar (50) not null,
    FamilyFavoriteSong varchar (100) not null
);

Create Table Friend (
    primary key id,
    FriendFirstName varchar (50) not null,
    FriendLastName varchar (50) not null,
    FriendBirthday varchar (50) not null,
    FriendWebsite varchar (100) not null,
    FriendEmail varchar (100) not null,
    FriendPhoneNumber int not null,
    FriendAddress varchar (150) not null,
    FriendCity varchar (50) not null,
    FriendState varchar (100) not null,
    FriendCountry varchar (50) not null,
    FriendContinent varchar (100) not null,
    FriendPlanet varchar (200) not null,
    FriendFavoriteColor varchar (50) not null,
    FriendFavoriteFood varchar (100) not null,
    FriendFavoriteDrink varchar (150) not null,
    FriendHobby varchar (100) not null,
    FriendTalent varchar (100) not null,
    FriendZodiacSign varchar (100) not null,
    FriendChineseZodiac varchar (100) not null,
    FriendDISC varchar (50) not null,
    FriendBusinessPersonalityType varchar (50) not null,
    FriendLearningType varchar (50) not null,
    FriendLoveLanguage varchar (50) not null,
    FriendSpiritAnimal varchar (100) not null,
    FriendLifeDreamGoal varchar (100) not null,
    FriendFavoriteSport varchar (50) not null,
    FriendFavoriteSong varchar (100) not null
);
    
create table Fan (
    primary key id,
    FanFirstName varchar (50) not null,
    FanLastName varchar (50) not null,
    FanBirthday varchar (50) not null,
    FanWebsite varchar (100) not null,
    FanEmail varchar (100) not null,
    FanPhoneNumber int not null,
    FanAddress varchar (150) not null,
    FanCity varchar (50) not null,
    FanState varchar (100) not null,
    FanCountry varchar (50) not null,
    FanContinent varchar (100) not null,
    FanPlanet varchar (200) not null,
    FanFavoriteColor varchar (50) not null,
    FanFavoriteFood varchar (100) not null,
    FanFavoriteDrink varchar (150) not null,
    FanHobby varchar (100) not null,
    FanTalent varchar (100) not null,
    FanZodiacSign varchar (100) not null,
    FanChineseZodiac varchar (100) not null,
    FanDISC varchar (50) not null,
    FanBusinessPersonalityType varchar (50) not null,
    FanLearningType varchar (50) not null,
    FanLoveLanguage varchar (50) not null,
    FanSpiritAnimal varchar (100) not null,
    FanLifeDreamGoal varchar (100) not null,
    FanFavoriteSport varchar (50) not null,
    FanFavoriteSong varchar (100) not null
);